# Generated by Django 5.0.2 on 2024-03-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='field may be empty', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalog.product'),
        ),
    ]
